name: irl_inventory
description: A new Flutter project.

publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=3.1.5 <4.0.0'

#--------------- PACKAGES ------------------#
dependencies:
  app_version_update: ^6.1.3
  capped_progress_indicator: ^0.0.2
  cloud_firestore: ^5.6.6
  connectivity_plus: ^6.1.3
  cupertino_icons: ^1.0.6
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_xlider: ^3.5.0
  get: ^4.6.6
  get_storage: ^2.1.1
  http: ^1.2.1
  iconsax: ^0.0.8
  intl: ^0.20.2
  logger: ^2.2.0
  lottie: ^3.3.1
  package_info_plus: ^8.3.0
  readmore: ^3.0.0
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  supabase_flutter: ^2.9.0
  url_launcher: ^6.2.6
  uuid: ^4.5.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/logos/

    - assets/images/content/

    - assets/images/animations/

    - assets/images/on_boarding_images/
    - assets/logos/robotics_lab_logo_black.png
    - assets/logos/robotics_lab_logo_white.png
    - assets/logos/wishlist_empty.png

  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#000000"
  image: assets/logos/robotics_lab_logo_black.png
  image_dark: assets/logos/robotics_lab_logo_white.png

  android_12:
    color: "#FFFFFF"
    color_dark: "#000000"
    image: assets/logos/robotics_lab_logo_black.png
    image_dark: assets/logos/robotics_lab_logo_white.png

  web: false
