import 'package:flutter/material.dart';

class MemeImage extends StatelessWidget {
  final String top;
  final String bottom;

  const MemeImage({required this.top, required this.bottom, Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final memeUrl = Uri.encodeFull(
        'https://api.memegen.link/images/custom/${Uri.encodeComponent(top)}/${Uri.encodeComponent(bottom)}.png?background=https://i.imgur.com/CsCgN7L.png');

    return Scaffold(
      appBar: AppBar(),
      body: Center(
        child: Padding(
          padding: const EdgeInsets.only(bottom: 100,left: 16, right: 16),
          child: Card(
            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
            elevation: 4,
            child: ClipRRect(
              borderRadius: BorderRadius.circular(12),
              child: Column(
                mainAxisSize: MainAxisSize.min,
                children: [
                  // Image widget with loading and error handling
                  Image.network(
                    memeUrl,
                    fit: BoxFit.contain,
                    loadingBuilder: (context, child, loadingProgress) {
                      if (loadingProgress == null) return child;
                      return Padding(
                        padding: const EdgeInsets.all(32.0),
                        child: Column(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: const [
                            CircularProgressIndicator(color: Colors.pink),
                            SizedBox(height: 16),
                            Text(
                              "Generating your Secret...",
                              style: TextStyle(fontSize: 16, color: Colors.grey),
                            ),
                          ],
                        ),
                      );
                    },
                    errorBuilder: (context, error, stackTrace) {
                      return const Padding(
                        padding: EdgeInsets.all(32.0),
                        child: Text(
                          "Oops! Failed to load meme.",
                          style: TextStyle(fontSize: 16, color: Colors.red),
                          textAlign: TextAlign.center,
                        ),
                      );
                    },
                  ),
                  // // Footer (optional)
                  // const Padding(
                  //   padding: EdgeInsets.all(8.0),
                  //   child: Text(
                  //     "Meme generated by Memegen.link",
                  //     style: TextStyle(fontSize: 12, color: Colors.grey),
                  //     textAlign: TextAlign.center,
                  //   ),
                  // ),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }
}
